version: '3.8'

services:
  db:
    image: timescale/timescaledb:latest-pg14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=priceguard
      - POSTGRES_PASSWORD=priceguard
      - POSTGRES_DB=priceguard
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U priceguard"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: web
    volumes:
      - .:/app
      - media_data:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://priceguard:priceguard@db:5432/priceguard
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=priceguard.settings

  celery_worker:
    build: .
    command: worker
    volumes:
      - .:/app
      - media_data:/app/media
    depends_on:
      - web
      - redis
    env_file:
      - .env
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://priceguard:priceguard@db:5432/priceguard
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=priceguard.settings

  celery_beat:
    build: .
    command: beat
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
    env_file:
      - .env
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://priceguard:priceguard@db:5432/priceguard
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=priceguard.settings

  flower:
    build: .
    command: flower
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    depends_on:
      - celery_worker
    env_file:
      - .env
    environment:
      - DEBUG=1
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=priceguard.settings

volumes:
  postgres_data:
  redis_data:
  media_data:
