version: '3.8'

services:
  db:
    image: timescale/timescaledb:latest-pg14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=priceguard
      - POSTGRES_PASSWORD=priceguard
      - POSTGRES_DB=priceguard
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://priceguard:priceguard@db:5432/priceguard
      - REDIS_URL=redis://redis:6379/0

  celery:
    build: ./backend
    command: celery -A priceguard worker -l INFO
    volumes:
      - ./backend:/app
    depends_on:
      - web
      - redis
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://priceguard:priceguard@db:5432/priceguard
      - REDIS_URL=redis://redis:6379/0

  celery-beat:
    build: ./backend
    command: celery -A priceguard beat -l INFO
    volumes:
      - ./backend:/app
    depends_on:
      - web
      - redis
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://priceguard:priceguard@db:5432/priceguard
      - REDIS_URL=redis://redis:6379/0

  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api

volumes:
  postgres_data: