# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: priceguard

---
# ConfigMap pour configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: priceguard-config
  namespace: priceguard
data:
  DEBUG: "0"
  ALLOWED_HOSTS: "*"
  CORS_ALLOWED_ORIGINS: "https://app.priceguard.io"

---
# Secret pour credentials
apiVersion: v1
kind: Secret
metadata:
  name: priceguard-secrets
  namespace: priceguard
type: Opaque
data:
  DATABASE_URL: <base64-encoded-url>
  REDIS_URL: <base64-encoded-url>
  SECRET_KEY: <base64-encoded-key>
  SENDGRID_API_KEY: <base64-encoded-key>
  FIREBASE_CREDENTIALS: <base64-encoded-json>

---
# Déploiement backend Django
apiVersion: apps/v1
kind: Deployment
metadata:
  name: priceguard-backend
  namespace: priceguard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: priceguard-backend
  template:
    metadata:
      labels:
        app: priceguard-backend
    spec:
      containers:
        - name: backend
          image: priceguard/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: priceguard-config
            - secretRef:
                name: priceguard-secrets
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20

---
# Service pour backend
apiVersion: v1
kind: Service
metadata:
  name: priceguard-backend
  namespace: priceguard
spec:
  selector:
    app: priceguard-backend
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP