apiVersion: apps/v1
kind: Deployment
metadata:
  name: priceguard-monitoring
  namespace: priceguard
  labels:
    app: priceguard
    component: monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: priceguard
      component: monitoring
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: priceguard
        component: monitoring
    spec:
      containers:
        - name: monitoring
          image: priceguard/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "priceguard.settings"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: priceguard-secrets
                  key: database-url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: priceguard-secrets
                  key: redis-url
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: priceguard-secrets
                  key: django-secret-key
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /api/health/
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health/
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
          volumeMounts:
            - name: timezone-config
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: timezone-config
          hostPath:
            path: /usr/share/zoneinfo/Europe/Paris
