apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: priceguard-monitoring-hpa
  namespace: priceguard
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: priceguard-monitoring
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: priceguard-celery-workers-hpa
  namespace: priceguard
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: priceguard-celery-workers
  minReplicas: 3
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
