# Déploiement scraper
apiVersion: apps/v1
kind: Deployment
metadata:
  name: priceguard-scraper
  namespace: priceguard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: priceguard-scraper
  template:
    metadata:
      labels:
        app: priceguard-scraper
    spec:
      containers:
        - name: scraper
          image: priceguard/scraper:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: priceguard-config
            - secretRef:
                name: priceguard-secrets
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "1Gi"

---
# HorizontalPodAutoscaler pour scraper
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: priceguard-scraper-hpa
  namespace: priceguard
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: priceguard-scraper
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80